[package]
name = "RUST-RAYTRACER"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rustRaytracer"
path = "src/lib.rs"

[dependencies]
rand = "0.7.3"
rayon = "1.3.0"
image = "*"
# glam = "*"